package com.albin.cartoonconundrum.bot.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NonNull;

@Data
@DynamoDBTable(tableName = "Cartoon")
public class Cartoon {

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    private String id;

    @NonNull
    @DynamoDBAttribute(attributeName = "Name")
    private String name;

    @DynamoDBAttribute(attributeName = "ImgUrl")
    private String imgUrl;

}
