package com.albin.cartoonconundrum.bot.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
@DynamoDBTable(tableName = "ChannelRelation")
public class ChannelRelation {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String cartoonId;
    private String discordChannelId;
    private boolean solved;
}
