package com.albin.cartoonconundrum.bot.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "ChannelRelation")
public class ChannelRelation {

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBHashKey(attributeName = "CartoonId")
    private String cartoonId;

    @DynamoDBHashKey(attributeName = "DiscordChannelId")
    private String discordChannelId;

    @DynamoDBHashKey(attributeName = "Solved")
    private boolean solved;

}
